# Generated by Django 5.1.4 on 2025-02-02 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment_admin_response'),
        ('products', '0002_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product'),
            preserve_default=False,
        ),
    ]
