# Generated by Django 5.1.4 on 2025-02-04 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comment_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='product',
        ),
    ]
