# Generated by Django 5.1.4 on 2025-01-30 10:58

import django.core.validators
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد تخفیف')),
                ('discount_percentage', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('valid_from', django_jalali.db.models.jDateTimeField(verbose_name='شروع اعتبار')),
                ('valid_to', django_jalali.db.models.jDateTimeField(verbose_name='پایان اعتبار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('apply_to_all', models.BooleanField(default=False, verbose_name='اعمال روی همه محصولات')),
                ('categories', models.ManyToManyField(blank=True, related_name='discounts', to='products.category', verbose_name='دسته\u200cبندی\u200cها')),
                ('products', models.ManyToManyField(blank=True, related_name='discounts', to='products.product', verbose_name='محصولات')),
            ],
        ),
    ]
