# Generated by Django 5.1.4 on 2025-02-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_section',
            field=models.CharField(blank=True, choices=[('featured', 'پیشنهاد ویژه'), ('discount', 'تخفیف\u200cدار'), ('new', 'جدیدترین\u200cها'), ('bestseller', 'پرفروش\u200cترین\u200cها')], max_length=20, null=True, verbose_name='نمایش در بخش'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
