# Generated by Django 5.1.4 on 2025-02-12 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_display_section_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='display_section',
        ),
    ]
